//API 1
GET http://localhost:3000/todos/?status=TO%20DO&priority=LOW&search_q=to
###
//API 1.1
GET http://localhost:3000/todos/?status=TO%20DO
###
//API 1.2
GET http://localhost:3000/todos/?priority=HIGH
###
//API 1.3
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###
//API 1.4
GET http://localhost:3000/todos/?search_q=to
###

//API 2
GET http://localhost:3000/todos/10/
###

//API 3
POST  http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

###

//API 4
PUT http://localhost:3000/todos/10
Content-Type: application/json

{
  "status": "TO DO"
}


###
//API 5
DELETE  http://localhost:3000/todos/10/
###